pipeline {
    agent any

    environment {
        IMAGE_NAME = "studentmarkservice-image"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Ayesha703/studentmarkservice.git',
                    credentialsId: 'abc'
            }
        }

        stage('Build Maven Project') {
            steps {
                bat "mvn clean package"
            }
        }

        stage('Build Docker Image') {
            steps {
                bat "docker build -t ${IMAGE_NAME}:latest -f Dockerfile ."
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                bat "kubectl apply -f sms-deployment.yaml"
            }
        }
    }

    post {
        success {
            echo "Jenkins pipeline completed successfully!"
        }
        failure {
            echo "Jenkins pipeline failed!"
        }
    }
}
