apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentmarkservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentmarkservice
  template:
    metadata:
      labels:
        app: studentmarkservice
    spec:
      containers:
        - name: studentmarkservice
          image: studentmarkservice-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8100
---
apiVersion: v1
kind: Service
metadata:
  name: studentmarkservice-service
spec:
  type: NodePort
  selector:
    app: studentmarkservice
  ports:
    - port: 8100
      targetPort: 8100
      nodePort: 30007
